=== dylmye/checkpac/lib/metadata.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Record<string,string>": {
            "type": "object"
        },
        "ServiceProviderData": {
            "description": "Shape of metadata.json objects",
            "properties": {
                "fullName": {
                    "description": "The trading name of the SP.",
                    "type": "string"
                },
                "id": {
                    "description": "The service provider's ID (SPID.)",
                    "maxLength": 3,
                    "minLength": 3,
                    "type": "string"
                },
                "instructions": {
                    "description": "A URL linking to specific instructions on how to\nget the PAC/STAC code from the SP.",
                    "format": "uri",
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "lastUpdated": {
                    "description": "The date YYYY-MM-DD that this SP was last updated.",
                    "format": "date",
                    "type": "string"
                },
                "logo": {
                    "description": "A URL pointing to an image representing the SP.",
                    "format": "uri",
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "shortName": {
                    "description": "The name most customers know the SP by.",
                    "type": "string"
                },
                "website": {
                    "description": "The homepage URL for the SP in your country.",
                    "format": "uri",
                    "type": "string"
                }
            },
            "required": [
                "fullName",
                "id",
                "instructions",
                "lastUpdated",
                "logo",
                "shortName",
                "website"
            ],
            "type": "object"
        }
    },
    "properties": {
        "aliases": {
            "$ref": "#/definitions/Record<string,string>",
            "description": "A key:value pair array, where the key is the alias and the value is the ID of the record it represents."
        },
        "dead": {
            "description": "A list of service providers that are no longer operating.",
            "items": {
                "$ref": "#/definitions/ServiceProviderData"
            },
            "type": "array"
        },
        "serviceProviders": {
            "description": "A list of service providers.",
            "items": {
                "$ref": "#/definitions/ServiceProviderData"
            },
            "type": "array"
        },
        "version": {
            "description": "The version of this metadata file.",
            "type": "string"
        }
    },
    "required": [
        "aliases",
        "dead",
        "serviceProviders",
        "version"
    ],
    "type": "object"
}

=== dylmye/checkpac/lib/metadata.json
{
    "$schema": "../lib/metadata.schema.json",
    "version": "1.2",
    "serviceProviders": [
        {
            "id": "BTC",
            "fullName": "BT Mobile Consumer",
            "shortName": "BT Mobile",
            "website": "https://www.bt.com/mobile",
            "instructions": "https://www.bt.com/help/mobile/how-do-i-get-a-pac-",
            "logo": "https://logo.clearbit.com/bt.com",
            "lastUpdated": "2021-04-22"
        },
        {
            "id": "ONE",
            "fullName": "EE",
            "shortName": "EE",
            "website": "https://ee.co.uk",
            "instructions": "https://ee.co.uk/help/help-new/managing-and-using-my-account/leaving-ee/what-is-a-pac-code",
            "logo": "https://logo.clearbit.com/ee.co.uk",
            "lastUpdated": "2021-04-22"
        },
        {
            "id": "GGF",
            "fullName": "Giffgaff",
            "shortName": "Giffgaff",
            "website": "https://www.giffgaff.com",
            "instructions": "https://www.giffgaff.com/help/articles/how-do-i-get-a-pac-code-to-leave-giffgaff",
            "logo": "https://logo.clearbit.com/giffgaff.com",
            "lastUpdated": "2021-04-22"
        },
        {
            "id": "VRG",
            "fullName": "Virgin Mobile",
            "shortName": "Virgin",
            "website": "https://www.virginmedia.com/mobile",
            "instructions": "https://www.virginmedia.com/help/mobile-switching-faqs#leaving",
            "logo": null,
            "lastUpdated": "2021-04-22"
        },
        {
            "id": "TEL",
            "fullName": "Telef√≥nica o2",
            "shortName": "o2",
            "website": "https://www.o2.co.uk",
            "instructions": "https://www.o2.co.uk/help/account-and-billing/switch#Thinkingofswitching",
            "logo": "https://logo.clearbit.com/o2.co.uk",
            "lastUpdated": "2021-04-22"
        },
        {
            "id": "HTG",
            "fullName": "Three Mobile",
            "shortName": "Three UK",
            "website": "https://www.three.co.uk",
            "instructions": "https://www.three.co.uk/support/switching/leaving-three",
            "logo": "https://logo.clearbit.com/three.co.uk",
            "lastUpdated": "2021-04-22"
        },
        {
            "id": "VTM",
            "fullName": "iD Mobile",
            "shortName": "iD",
            "website": "https://www.idmobile.co.uk",
            "instructions": "https://www.idmobile.co.uk/help-and-support/leaving-id",
            "logo": "https://logo.clearbit.com/idmobile.co.uk",
            "lastUpdated": "2021-04-24"
        },
        {
            "id": "LEB",
            "fullName": "Lebara Mobile",
            "shortName": "Lebara",
            "website": "https://mobile.lebara.com/gb/en/",
            "instructions": "https://mobile.lebara.com/gb/en/leave-lebara",
            "logo": "https://logo.clearbit.com/lebara.com",
            "lastUpdated": "2022-03-15"
        },
        {
            "id": "VUK",
            "fullName": "Vodafone / Voxi",
            "shortName": "Vodafone / Voxi",
            "website": "https://www.vodafone.co.uk/",
            "instructions": "https://www.vodafone.co.uk/help-and-information/cancel-your-account",
            "logo": "https://logo.clearbit.com/vodafone.co.uk",
            "lastUpdated": "2022-03-15"
        },
        {
            "id": "LCS",
            "fullName": "Three Smarty",
            "shortName": "SMARTY",
            "website": "https://smarty.co.uk/",
            "instructions": "https://help.smarty.co.uk/en/articles/952726",
            "logo": "https://logo.clearbit.com/smarty.co.uk",
            "lastUpdated": "2022-03-16"
        },
        {
            "id": "TKM",
            "fullName": "Talkmobile",
            "shortName": "Talkmobile",
            "website": "https://talkmobile.co.uk/",
            "instructions": "https://talkmobile.co.uk/switching",
            "logo": "https://logo.clearbit.com/talkmobile.co.uk",
            "lastUpdated": "2022-03-16"
        }
    ],
    "aliases": {
        "TSL": "VTM",
        "VCN": "VUK",
        "VOD": "VUK",
        "H3G": "HTG",
        "CEL": "TEL"
    },
    "dead": [
        {
            "id": "ORG",
            "fullName": "Orange",
            "shortName": "Orange",
            "website": "https://orange.co.uk/",
            "instructions": "https://orange.co.uk/",
            "logo": "https://logo.clearbit.com/orange.co.uk",
            "lastUpdated": "2022-03-16"
        },
        {
            "id": "ONE",
            "fullName": "T-Mobile",
            "shortName": "T-Mobile",
            "website": "https://t-mobile.co.uk/",
            "instructions": "https://t-mobile.co.uk/",
            "logo": "https://logo.clearbit.com/telekom.com",
            "lastUpdated": "2022-03-16"
        }
    ]
}
